services:
  - type: web
    name: kts-stripe-server
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 4242
      - key: STRIPE_SECRET_KEY
        sync: false

  - type: web
    name: kts-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_APP_NAME
        value: Kigali Tech Store
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: VITE_STRIPE_SERVER_URL
        sync: false
